const NOTES = {
      'C4': require('./C4.mp3'), 
      'D4': require('./D4.mp3'), 
      'E4': require('./E4.mp3'), 
      'F4': require('./F4.mp3'), 
      'G4': require('./G4.mp3'), 
      'A4': require('./A4.mp3'), 
      'B4': require('./B4.mp3'),
      'A04': require('./A04.mp3'), 
      'G04': require('./G04.mp3'), 
      'D04': require('./D04.mp3'), 
      'C5': require('./C5.mp3'),
      'beatbass': require('./beatbass.mp3'), 
      'bassloop': require('./bassloop.mp3'), 
      'bass1': require('./bass1.mp3'), 
      'bass2': require('./bass2.mp3'), 
      'bass3': require('./bass3.mp3'), 
      'bass4': require('./bass4.mp3'), 
      'bass5': require('./bass5.mp3'), 
      'bass6': require('./bass6.mp3'),
      'bass8': require('./bass8.mp3'), 
      'bass10': require('./bass10.mp3'), 
      'bass11': require('./bass11.mp3'), 
      'RaccoonCityMassacreBeat': require('./RaccoonCityMassacreBeat.mp3'),
}
export default NOTES;