const NOTES = {
      'C4': require('./C4.mp3'), 
      'D4': require('./D4.mp3'), 
      'E4': require('./E4.mp3'), 
      'F4': require('./F4.mp3'), 
      'G4': require('./G4.mp3'), 
      'A4': require('./A4.mp3'), 
      'B4': require('./B4.mp3'),
      'A04': require('./A04.mp3'), 
      'G04': require('./G04.mp3'), 
      'D04': require('./D04.mp3'), 
      'C5': require('./C5.mp3'),
      'beatbass': require('./beatbass.mp3'), 
      'bassloop': require('./bassloop.mp3'), 
      'bass1': require('./whoo.mp3'), 
      'bass2': require('./scratch.mp3'), 
      'bass3': require('./scratch2.mp3'), 
      'bass4': require('./scratch3.mp3'), 
      'bass5': require('./bazz1.mp3'), 
      'bass6': require('./bazz2.mp3'),
      'bass8': require('./bazz3.mp3'), 
      'bass10': require('./bazz4.mp3'), 
      'bass11': require('./yeah.mp3'), 
      'RaccoonCityMassacreBeat': require('./RaccoonCityMassacreBeat.mp3'),
}
export default NOTES;